# author: brian marwa
# email: kidbrion7@gmail.com
# run cmd: eksctl create cluster -f BE-cluster-v1.yaml


apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: BE-cluster-v1
  region: eu-west-1

nodeGroups:
  - name: ng-BE-cluster-v1-1
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 3
