apiVersion: v1
kind: Service
metadata:
  name: burymeahatchet-nlb-service
  namespace: be
spec:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  ports:
    - port: 80
      targetPort: 8000
  selector:
    name: burymeahatchet


